# User Configuration File
#
# This file contains user-editable settings that control the behavior of the prediction model.
# Changes to this file take effect when the application is restarted.
#
# SECTIONS:
# - api_keys: Integration with external data providers
# - dashboard: UI configuration and display preferences
# - features: Feature toggles for model inputs
# - hardware: System resource allocation settings
# - hyperparameter: Settings for the model tuning process
# - model: Model architecture and training configuration
# - tickers: Stock/crypto symbols to analyze
# - time_series: Time window settings for analysis
# - toggles: Global feature toggles
# - training: Model training behavior settings

api_keys:
  # Rate limiting for API calls to prevent exceeding quotas
  coingecko_rate_limit_sleep: 1.5
  defaults:
    # Default API keys (replace with your own keys for full functionality)
    alphavantage_api_key: ''
    coingecko_api_key: ''
    finnhub_api_key: ''
  file_path: config/api_keys.yaml

dashboard:
  autorefresh_interval_sec: 60
  realtime_update: true
  show_prediction_plots: true
  show_prediction_plots_interval: 5
  show_training_history: true
  show_weight_histograms: true
  use_caching: true
  update_during_walk_forward: true  # Controls whether to update dashboard during walk-forward validation
  visualization:
    chart_height: 600
    color_theme: default
    indicators:
      show_bb: false
      show_ma: false
      show_macd: false
      show_rsi: false
    lookback: 60
    show_volume: true

features:
  toggles:
    atr: true
    bollinger_bands: true
    macd: true
    obv: true
    rsi: true
    sentiment: false
    vmli: true
    werpi: true

hardware:
  enable_xla: true
  gpu_memory_fraction: auto
  omp_num_threads: 4
  use_directml: true
  use_gpu: true
  use_mixed_precision: false
  use_xla: true
  memory_growth: true     

hyperparameter:
  adaptive:
    threshold: true
    window_size: true
  auto_run_tuning: false
  default_mode: normal
  n_startup_trials: 10000
  thresholds:
    mape: 5.0
    rmse: 500
  tuning_modes:
    extreme:
      complexity_multiplier: 2.0
      epochs_multiplier: 3.0
      timeout_multiplier: 15.0
      trials_multiplier: 10.0
    normal:
      complexity_multiplier: 1.0
      epochs_multiplier: 1.0
      timeout_multiplier: 1.0
      trials_multiplier: 1.0
    quick:
      complexity_multiplier: 0.5
      epochs_multiplier: 0.3
      timeout_multiplier: 0.2
      trials_multiplier: 0.25
    thorough:
      complexity_multiplier: 1.5
      epochs_multiplier: 2.0
      timeout_multiplier: 4.0
      trials_multiplier: 3.0

incremental_learning:
  retraining:
    threshold: 0.1
  model_saving: # Thresholds to start saving models for incremental learning and auto retraining
    rmse_threshold: 50000
    mape_threshold: 50
  max_saved_models: 100

logger:
  retention:
    max_files: 1  # Maximum number of log files to keep
    max_age_days: 30  # Delete logs older than this many days
    auto_cleanup: true  # Enable automatic cleanup

model:
  active_model_types:
    nbeats: true
    cnn: true
    lstm: true
    ltc: true
    random_forest: true
    rnn: true
    tabnet: true
    tft: true
    xgboost: true
  default_forecast_horizon: 30
  default_lookback: 30
  ensemble_mode: weighted_average

tickers:
  default: ETH-USD
  symbols:
  - ETH-USD
  - BTC-USD
  - LINK-USD
  - LTC-USD
  - AAVE-USD
  - AVAX-USD
  - SOL-USD
  - MATIC-USD
  - RVN-USD
  - GOOGL
  - T
  - AMZN
  - NVDA
  - MSFT
  - META
  - STLA
  - AMD
  - INTC
  - SQ
  - NET
  - ZM
  - ROKU
  - AAPL
  - TSLA
  - NFLX
  - SPY
  - ARK
  - KBWB
  - XLC

time_series:
  apply_weekend_gap: true
  default_interval: 1d
  prediction_horizon: 30
  timeframes:
  - 1d
  - 3d
  - 1wk
  - 1h
  - 2h
  - 4h
  - 6h
  - 8h
  - 12h
  - 1mo
  - 1m
  - 5m
  - 15m
  - 30m

toggles:
  apply_weekend_gap: true
  enable_email_alerts: false

training:
  cleanup_old_logs: true
  continue_from_weights: true
  random_state:
    mode: 'off'
    value: 42
